[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#9c1b2e"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#333333"
font = "sans serif"
